language: csharp
mono: none
dotnet: 2.0.0-preview1-005977
dist: trusty
solution: CIV.sln
install: ./dotnet-install.sh

env:
    # Set the DOTNET_SKIP_FIRST_TIME_EXPERIENCE environment variable to stop wasting time caching packages
  - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    # Disable sending usage data to Microsoft
  - DOTNET_CLI_TELEMETRY_OPTOUT=true

script:
  - dotnet restore
  - dotnet build CIV/CIV.csproj -c Release
  - dotnet test CIV.Test/CIV.Test.csproj
