# language: csharp
# mono: none
# dotnet: 2.0.0-preview1-005977
# dist: trusty
# solution: CIV.sln
os:
  - osx
osx_image: xcode8.3
install: ./dotnet-install.sh

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true 
    - DOTNET_CLI_TELEMETRY_OPTOUT=true

script:
  - /Users/travis/.dotnet/dotnet restore
  - /Users/travis/.dotnet/dotnet build CIV/CIV.csproj -c Release
  - /Users/travis/.dotnet/dotnet test CIV.Test/CIV.Test.csproj
