os:
  - osx
osx_image: xcode8.3
install: ./dotnet-install.sh
language: generic

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true 
    - DOTNET_CLI_TELEMETRY_OPTOUT=true

script:
  - /Users/travis/.dotnet/dotnet restore --disable-parallel
  - /Users/travis/.dotnet/dotnet build -c Release
  - /Users/travis/.dotnet/dotnet test CIV.Test/CIV.Test.csproj

notifications:
  email:
    on_success: change
    on_failure: change