//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Users/luca/Projects/CIV/CIV/ccs/CcsParser.g4 by ANTLR 4.5.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace CIV.Ccs {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CcsParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3")]
[System.CLSCompliant(false)]
public interface ICcsParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by the <c>relabelProc</c>
	/// labeled alternative in <see cref="CcsParser.process"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelabelProc([NotNull] CcsParser.RelabelProcContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>relabelProc</c>
	/// labeled alternative in <see cref="CcsParser.process"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelabelProc([NotNull] CcsParser.RelabelProcContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>prefixProc</c>
	/// labeled alternative in <see cref="CcsParser.process"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrefixProc([NotNull] CcsParser.PrefixProcContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>prefixProc</c>
	/// labeled alternative in <see cref="CcsParser.process"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrefixProc([NotNull] CcsParser.PrefixProcContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>restrictIdProc</c>
	/// labeled alternative in <see cref="CcsParser.process"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRestrictIdProc([NotNull] CcsParser.RestrictIdProcContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>restrictIdProc</c>
	/// labeled alternative in <see cref="CcsParser.process"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRestrictIdProc([NotNull] CcsParser.RestrictIdProcContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>parenthProc</c>
	/// labeled alternative in <see cref="CcsParser.process"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenthProc([NotNull] CcsParser.ParenthProcContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>parenthProc</c>
	/// labeled alternative in <see cref="CcsParser.process"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenthProc([NotNull] CcsParser.ParenthProcContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>nilProc</c>
	/// labeled alternative in <see cref="CcsParser.process"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNilProc([NotNull] CcsParser.NilProcContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>nilProc</c>
	/// labeled alternative in <see cref="CcsParser.process"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNilProc([NotNull] CcsParser.NilProcContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>restrictExprProc</c>
	/// labeled alternative in <see cref="CcsParser.process"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRestrictExprProc([NotNull] CcsParser.RestrictExprProcContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>restrictExprProc</c>
	/// labeled alternative in <see cref="CcsParser.process"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRestrictExprProc([NotNull] CcsParser.RestrictExprProcContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>parProc</c>
	/// labeled alternative in <see cref="CcsParser.process"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParProc([NotNull] CcsParser.ParProcContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>parProc</c>
	/// labeled alternative in <see cref="CcsParser.process"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParProc([NotNull] CcsParser.ParProcContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>choiceProc</c>
	/// labeled alternative in <see cref="CcsParser.process"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChoiceProc([NotNull] CcsParser.ChoiceProcContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>choiceProc</c>
	/// labeled alternative in <see cref="CcsParser.process"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChoiceProc([NotNull] CcsParser.ChoiceProcContext context);

	/// <summary>
	/// Enter a parse tree produced by the <c>pidProc</c>
	/// labeled alternative in <see cref="CcsParser.process"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPidProc([NotNull] CcsParser.PidProcContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>pidProc</c>
	/// labeled alternative in <see cref="CcsParser.process"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPidProc([NotNull] CcsParser.PidProcContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CcsParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] CcsParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CcsParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] CcsParser.ProgramContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CcsParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLine([NotNull] CcsParser.LineContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CcsParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLine([NotNull] CcsParser.LineContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CcsParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] CcsParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CcsParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] CcsParser.StatementContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CcsParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComment([NotNull] CcsParser.CommentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CcsParser.comment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComment([NotNull] CcsParser.CommentContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CcsParser.procDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcDef([NotNull] CcsParser.ProcDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CcsParser.procDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcDef([NotNull] CcsParser.ProcDefContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CcsParser.setDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetDef([NotNull] CcsParser.SetDefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CcsParser.setDef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetDef([NotNull] CcsParser.SetDefContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CcsParser.process"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProcess([NotNull] CcsParser.ProcessContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CcsParser.process"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProcess([NotNull] CcsParser.ProcessContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CcsParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabel([NotNull] CcsParser.LabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CcsParser.label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabel([NotNull] CcsParser.LabelContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CcsParser.pid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPid([NotNull] CcsParser.PidContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CcsParser.pid"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPid([NotNull] CcsParser.PidContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CcsParser.relabelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelabelExpression([NotNull] CcsParser.RelabelExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CcsParser.relabelExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelabelExpression([NotNull] CcsParser.RelabelExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CcsParser.relabelList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelabelList([NotNull] CcsParser.RelabelListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CcsParser.relabelList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelabelList([NotNull] CcsParser.RelabelListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CcsParser.relabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelabel([NotNull] CcsParser.RelabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CcsParser.relabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelabel([NotNull] CcsParser.RelabelContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CcsParser.setVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetVar([NotNull] CcsParser.SetVarContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CcsParser.setVar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetVar([NotNull] CcsParser.SetVarContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CcsParser.setId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetId([NotNull] CcsParser.SetIdContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CcsParser.setId"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetId([NotNull] CcsParser.SetIdContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CcsParser.setExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetExpression([NotNull] CcsParser.SetExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CcsParser.setExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetExpression([NotNull] CcsParser.SetExpressionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CcsParser.setList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSetList([NotNull] CcsParser.SetListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CcsParser.setList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSetList([NotNull] CcsParser.SetListContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CcsParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAction([NotNull] CcsParser.ActionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CcsParser.action"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAction([NotNull] CcsParser.ActionContext context);

	/// <summary>
	/// Enter a parse tree produced by <see cref="CcsParser.nonTauAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNonTauAction([NotNull] CcsParser.NonTauActionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CcsParser.nonTauAction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNonTauAction([NotNull] CcsParser.NonTauActionContext context);
}
} // namespace CIV.Ccs
