//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from HmlParser.g4 by ANTLR 4.5.3

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace CIV.Hml {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IHmlParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3")]
[System.CLSCompliant(false)]
public partial class HmlParserBaseListener : IHmlParserListener {
	/// <summary>
	/// Enter a parse tree produced by the <c>WeakDiamond</c>
	/// labeled alternative in <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWeakDiamond([NotNull] HmlParser.WeakDiamondContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>WeakDiamond</c>
	/// labeled alternative in <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWeakDiamond([NotNull] HmlParser.WeakDiamondContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>BoxAll</c>
	/// labeled alternative in <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoxAll([NotNull] HmlParser.BoxAllContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>BoxAll</c>
	/// labeled alternative in <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoxAll([NotNull] HmlParser.BoxAllContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>Conj</c>
	/// labeled alternative in <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConj([NotNull] HmlParser.ConjContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Conj</c>
	/// labeled alternative in <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConj([NotNull] HmlParser.ConjContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>True</c>
	/// labeled alternative in <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTrue([NotNull] HmlParser.TrueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>True</c>
	/// labeled alternative in <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTrue([NotNull] HmlParser.TrueContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>Box</c>
	/// labeled alternative in <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBox([NotNull] HmlParser.BoxContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Box</c>
	/// labeled alternative in <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBox([NotNull] HmlParser.BoxContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>Diamond</c>
	/// labeled alternative in <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDiamond([NotNull] HmlParser.DiamondContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Diamond</c>
	/// labeled alternative in <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDiamond([NotNull] HmlParser.DiamondContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>False</c>
	/// labeled alternative in <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFalse([NotNull] HmlParser.FalseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>False</c>
	/// labeled alternative in <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFalse([NotNull] HmlParser.FalseContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>WeakDiamondAll</c>
	/// labeled alternative in <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWeakDiamondAll([NotNull] HmlParser.WeakDiamondAllContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>WeakDiamondAll</c>
	/// labeled alternative in <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWeakDiamondAll([NotNull] HmlParser.WeakDiamondAllContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>Parenth</c>
	/// labeled alternative in <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenth([NotNull] HmlParser.ParenthContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Parenth</c>
	/// labeled alternative in <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenth([NotNull] HmlParser.ParenthContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>WeakBox</c>
	/// labeled alternative in <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWeakBox([NotNull] HmlParser.WeakBoxContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>WeakBox</c>
	/// labeled alternative in <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWeakBox([NotNull] HmlParser.WeakBoxContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>Negated</c>
	/// labeled alternative in <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNegated([NotNull] HmlParser.NegatedContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Negated</c>
	/// labeled alternative in <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNegated([NotNull] HmlParser.NegatedContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>WeakBoxAll</c>
	/// labeled alternative in <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWeakBoxAll([NotNull] HmlParser.WeakBoxAllContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>WeakBoxAll</c>
	/// labeled alternative in <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWeakBoxAll([NotNull] HmlParser.WeakBoxAllContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>Disj</c>
	/// labeled alternative in <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDisj([NotNull] HmlParser.DisjContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Disj</c>
	/// labeled alternative in <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDisj([NotNull] HmlParser.DisjContext context) { }

	/// <summary>
	/// Enter a parse tree produced by the <c>DiamondAll</c>
	/// labeled alternative in <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDiamondAll([NotNull] HmlParser.DiamondAllContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DiamondAll</c>
	/// labeled alternative in <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDiamondAll([NotNull] HmlParser.DiamondAllContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="HmlParser.labelList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabelList([NotNull] HmlParser.LabelListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HmlParser.labelList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabelList([NotNull] HmlParser.LabelListContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="HmlParser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLabel([NotNull] HmlParser.LabelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HmlParser.label"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLabel([NotNull] HmlParser.LabelContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="HmlParser.baseHml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBaseHml([NotNull] HmlParser.BaseHmlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HmlParser.baseHml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBaseHml([NotNull] HmlParser.BaseHmlContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterHml([NotNull] HmlParser.HmlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="HmlParser.hml"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitHml([NotNull] HmlParser.HmlContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace CIV.Hml
